version: '3.9'

services:
    app:
        container_name: ${PROJECT_NAME}_app
        build:
            context: .
            dockerfile: ./vendor_docker/server/php/php.dockerfile
            args:
                USER_ID: ${USER_ID:-0}
                GROUP_ID: ${GROUP_ID:-0}
                PHP_VERSION: ${PHP_VERSION:-8.0}
        depends_on:
            - db
        volumes:
            - ./../:/var/www/html/public
            - ./vendor_docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
        ports:
            - "${SERVER_PORT:-80}:80"
            - "4443:443"
            - "${WEBSOCKETS_PORT:-8090}:8080"

    db:
        container_name: ${PROJECT_NAME}_db
        image: mariadb
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: bitcom
            MYSQL_PASSWORD: ${DB_PWD}
        volumes:
            - ./volumes/mysql/data:/var/lib/mysql
        ports:
            - "${DB_PORT:-3306}:3306"

    cron:
        container_name: ${PROJECT_NAME}_cron
        build:
            context: .
            dockerfile: ./vendor_docker/server/php/php.dockerfile
        volumes:
            - ./../:/var/www/html/public
            - ./vendor_docker/server/cron:/etc/cron.d/cron

    redis:
        image: redis:alpine
        container_name: ${PROJECT_NAME}_redis
        volumes:
            - ./volumes/redis:/data
        restart: on-failure
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        ports:
            - "${REDIS_PORT:-6379}:6379"
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
